#:schema ./.vscode/schemas/vscode-extensions.json

name = "vscode-problem-matcher"
private = true
version = "0.1.0"
displayName = "Tasks Problem Matchers"
description = "VS Code tasks problem matchers for daily development."
icon = "./assets/icon.png"
publisher = "sherluok"
main = "./out/vscode.js"
activationEvents = [ "onCommand:workbench.action.tasks.runTask" ]
[scripts]
link = "node --import tsx src/link.ts"
watch = "esbuild src/vscode.ts src/execution.ts --bundle --outdir=out --sourcemap --platform=node --target=node20.18.1 --packages=external --watch"
[devDependencies]
'@types/node' = "^22.10.3"
'@types/vscode' = "^1.94.0"
devtools-protocol = "^0.0.1404580"
esbuild = "^0.24.2"
tsx = "^4.17.0"
typescript = "^5.7.3"
[engines]
vscode = "1.96.2"
[contributes]
[contributes.icons]
[contributes.icons.logo-esbuild]
description = "esbuild logo"
[contributes.icons.logo-esbuild.default]
fontPath = "./assets/icon/font/brand.woff2"
fontCharacter = "\\E601"
[contributes.icons.logo-webpack]
description = "Webpack logo"
[contributes.icons.logo-webpack.default]
fontPath = "./assets/icon/font/brand.woff2"
fontCharacter = "\\E602"
[contributes.icons.logo-react]
description = "React logo"
[contributes.icons.logo-react.default]
fontPath = "./assets/icon/font/brand.woff2"
fontCharacter = "\\E603"
[contributes.icons.logo-cloudflare]
description = "Cloudflare logo"
[contributes.icons.logo-cloudflare.default]
fontPath = "./assets/icon/font/brand.woff2"
fontCharacter = "\\E604"
[contributes.icons.logo-node]
description = "Node.js logo"
[contributes.icons.logo-node.default]
fontPath = "./assets/icon/font/brand.woff2"
fontCharacter = "\\E605"
[[contributes.problemPatterns]]
name = "rollup"
[[contributes.problemPatterns.patterns]]
regexp = "^\\[!\\] RollupError: \\[plugin typescript\\] .+ @rollup\\/plugin-typescript TS(?<errorCode>\\d+): (?<message>.+)\\r?\\n(?<file>.*?):\\s*\\((?<line>\\d+):(?<column>\\d+)\\)$"
file = 3
line = 4
column = 5
code = 1
message = 2
[[contributes.problemPatterns.patterns]]
regexp = "^\\(!\\) \\[plugin typescript\\] .+ @rollup\\/plugin-typescript TS(?<errorCode>\\d+): (?<message>.+)\\r?\\n(?<file>.*?):\\s*\\((?<line>\\d+):(?<column>\\d+)\\)$"
file = 3
line = 4
column = 5
code = 1
message = 2
[[contributes.problemMatchers]]
name = "esbuild"
owner = "typescript"
fileLocation = "relative"
pattern = "$rollup"
[contributes.problemMatchers.background]
activeOnStart = true
beginsPattern = "^esbuild start$"
endsPattern = "^esbuild end$"
[[contributes.problemMatchers]]
name = "webpack"
owner = "typescript"
fileLocation = "relative"
pattern = "$rollup"
[contributes.problemMatchers.background]
activeOnStart = true
beginsPattern = "^\\[webpack\\] compilation start\\.$"
endsPattern = "^\\[webpack\\] compilation end\\.$"
[[contributes.problemMatchers]]
name = "wrangler"
owner = "typescript"
fileLocation = "relative"
[contributes.problemMatchers.pattern]
regexp = "^(?<file>.+\\.rs):(?<line>\\d+):(?<col>\\d+):\\s+(?<message>.*)$"
file = 1
line = 2
column = 3
message = 4
[contributes.problemMatchers.background]
activeOnStart = true
beginsPattern = "(Starting|Reloading) local server\\.\\.\\."
endsPattern = "(Ready|Updated and ready) on"
[[contributes.problemMatchers]]
name = "common"
owner = "typescript"
fileLocation = "relative"
[contributes.problemMatchers.pattern]
regexp = "^([^\\s].*)[\\(:](\\d+)[,:](\\d+)(?:\\):\\s+|\\s+-\\s+)(error|warning|info)\\s+TS(\\d+)\\s*:\\s*(.*)$"
file = 1
line = 2
column = 3
severity = 4
code = 5
message = 6
[contributes.problemMatchers.background]
activeOnStart = true
beginsPattern = "^vscode background task begins pattern"
endsPattern = "^vscode background task ends pattern"
[[contributes.taskDefinitions]]
type = "open-browser-page"
required = [ "remoteDebuggingPort" ]
[contributes.taskDefinitions.properties]
[contributes.taskDefinitions.properties.remoteDebuggingPort]
type = "number"
description = "The Rake task to customize"
[contributes.taskDefinitions.properties.makesureOpenPageUrl]
type = "string"
description = "The Rake file that provides the task. Can be omitted."
